"""Integrator - applies validated patches to the codebase."""

from pathlib import Path
from typing import Optional

import git

from phoenix.core.logging import get_logger
from phoenix.core.models import Patch
from phoenix.programmer.code_editor import CodeEditor

logger = get_logger(__name__)


class Integrator:
    """Integrates validated patches into the codebase."""
    
    def __init__(self, project_path: Path):
        """
        Initialize integrator.
        
        Args:
            project_path: Path to the project
        """
        self.project_path = project_path
        self.code_editor = CodeEditor(project_path)
        self.logger = get_logger(__name__)
        
        # Initialize git repo if present
        try:
            self.repo = git.Repo(project_path)
        except git.InvalidGitRepositoryError:
            self.repo = None
            self.logger.warning("not_a_git_repository", path=str(project_path))
    
    def integrate_patch(
        self,
        patch: Patch,
        create_commit: bool = True,
        commit_message: Optional[str] = None,
    ) -> bool:
        """
        Integrate a validated patch into the codebase.
        
        Args:
            patch: The validated patch to apply
            create_commit: Whether to create a git commit
            commit_message: Custom commit message
            
        Returns:
            True if successful
        """
        self.logger.info(
            "integrating_patch",
            patch_id=str(patch.id),
            file=patch.file_path,
        )
        
        try:
            # Apply the patch
            self.code_editor.write_file(patch.file_path, patch.patched_content)
            
            # Create git commit if requested
            if create_commit and self.repo:
                message = commit_message or self._generate_commit_message(patch)
                self._create_commit(patch.file_path, message)
            
            self.logger.info(
                "patch_integrated",
                patch_id=str(patch.id),
                file=patch.file_path,
            )
            
            return True
            
        except Exception as e:
            self.logger.error(
                "integration_failed",
                patch_id=str(patch.id),
                error=str(e),
            )
            return False
    
    def rollback_patch(self, patch: Patch) -> bool:
        """
        Rollback a patch to original content.
        
        Args:
            patch: The patch to rollback
            
        Returns:
            True if successful
        """
        self.logger.info(
            "rolling_back_patch",
            patch_id=str(patch.id),
            file=patch.file_path,
        )
        
        try:
            if patch.original_content:
                self.code_editor.write_file(
                    patch.file_path, patch.original_content
                )
                
                if self.repo:
                    self._create_commit(
                        patch.file_path,
                        f"Rollback Phoenix patch {patch.id}",
                    )
                
                self.logger.info("patch_rolled_back", patch_id=str(patch.id))
                return True
            else:
                self.logger.warning(
                    "no_original_content_for_rollback",
                    patch_id=str(patch.id),
                )
                return False
                
        except Exception as e:
            self.logger.error(
                "rollback_failed",
                patch_id=str(patch.id),
                error=str(e),
            )
            return False
    
    def _generate_commit_message(self, patch: Patch) -> str:
        """Generate a commit message for a patch."""
        return f"[Phoenix] {patch.description}\n\nAutomatically generated by Phoenix self-healing runtime.\nPatch ID: {patch.id}"
    
    def _create_commit(self, file_path: str, message: str) -> None:
        """Create a git commit."""
        if not self.repo:
            return
        
        try:
            # Stage the file
            self.repo.index.add([file_path])
            
            # Commit
            self.repo.index.commit(message)
            
            self.logger.info("git_commit_created", file=file_path)
            
        except Exception as e:
            self.logger.warning("git_commit_failed", error=str(e))
