#!/bin/bash
# Phoenix Framework - Quick Command Reference
# Run this to see all available commands

echo ""
echo ""
echo "          PHOENIX FRAMEWORK"
echo "       Quick Command Reference"
echo ""
echo ""

echo " SYSTEM VALIDATION"
echo "═══════════════════════════════════════════════════════════"
echo " python validate.py       - Run complete system check"
echo " pytest tests/ -v        - Run unit tests"
echo " python -m pytest --cov=phoenix - Run with coverage"
echo ""

echo " DEMO & EXECUTION"
echo "═══════════════════════════════════════════════════════════"
echo " python demo.py         - Run interactive demo"
echo " python -m phoenix.api.main   - Start API server"
echo " docker-compose up -d      - Start all services"
echo " docker-compose down       - Stop all services"
echo ""

echo " DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════"
echo " cat README.md          - Project overview"
echo " cat QUICKSTART.md        - Quick start guide"
echo " cat USAGE.md          - Detailed usage"
echo " cat ARCHITECTURE.md       - System architecture"
echo " cat FINAL_YEAR_PROJECT.md    - Presentation guide"
echo " cat PRODUCTION_CHECKLIST.md   - Deployment checklist"
echo " cat COMPLETION_REPORT.md    - Status report"
echo ""

echo " CONFIGURATION"
echo "═══════════════════════════════════════════════════════════"
echo " cp .env.example .env      - Create environment file"
echo " nano .env            - Edit configuration"
echo " cat .env.example        - View config template"
echo ""

echo " DATABASE"
echo "═══════════════════════════════════════════════════════════"
echo " docker-compose up -d postgres  - Start PostgreSQL"
echo " python -m phoenix.knowledge.initialize_db - Setup database"
echo " docker exec -it phoenix-postgres psql -U phoenix - Connect to DB"
echo ""

echo " DEBUGGING"
echo "═══════════════════════════════════════════════════════════"
echo " tail -f logs/phoenix.log    - View logs"
echo " docker-compose logs -f     - View container logs"
echo " python -m pip list       - List installed packages"
echo " python -c 'import phoenix'   - Test Phoenix import"
echo ""

echo " TESTING"
echo "═══════════════════════════════════════════════════════════"
echo " pytest tests/test_observer.py  - Test Observer layer"
echo " pytest tests/test_critic.py   - Test Critic layer"
echo " pytest tests/ -k test_name   - Run specific test"
echo " pytest tests/ -v --tb=short   - Verbose with short trace"
echo ""

echo " DEPENDENCIES"
echo "═══════════════════════════════════════════════════════════"
echo " pip install -r requirements.txt - Install dependencies"
echo " pip list            - Show installed packages"
echo " pip install --upgrade phoenix  - Upgrade Phoenix"
echo ""

echo " API ENDPOINTS (when server running)"
echo "═══════════════════════════════════════════════════════════"
echo " http://localhost:8000      - API root"
echo " http://localhost:8000/docs   - Interactive docs (Swagger)"
echo " http://localhost:8000/redoc   - ReDoc documentation"
echo " http://localhost:8000/health  - Health check"
echo ""

echo " DEVELOPMENT"
echo "═══════════════════════════════════════════════════════════"
echo " mypy phoenix/          - Type checking"
echo " black phoenix/         - Code formatting"
echo " pylint phoenix/         - Linting"
echo " git status           - Check git status"
echo ""

echo " QUICK START WORKFLOW"
echo "═══════════════════════════════════════════════════════════"
echo " 1. python validate.py      # Validate system"
echo " 2. cp .env.example .env     # Create config"
echo " 3. nano .env          # Add API keys"
echo " 4. python demo.py        # Run demo"
echo " 5. python -m phoenix.api.main  # Start API"
echo ""

echo " EXAMPLE USAGE"
echo "═══════════════════════════════════════════════════════════"
echo " # Analyze a project"
echo " python -c \""
echo " from phoenix.orchestrator.orchestrator import Orchestrator"
echo " o = Orchestrator(project_path='examples/calculator-buggy')"
echo " result = o.run()"
echo " print(f'Fixed: {result.repaired_count} failures')"
echo " \""
echo ""

echo " PRESENTATION SHORTCUTS"
echo "═══════════════════════════════════════════════════════════"
echo " python validate.py && python demo.py - Quick validation + demo"
echo " cat FINAL_YEAR_PROJECT.md | less   - Read presentation guide"
echo " cat COMPLETION_REPORT.md | less   - Read status report"
echo ""

echo "🆘 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════════"
echo " If imports fail:"
echo "  pip install -r requirements.txt --force-reinstall"
echo "  python validate.py"
echo ""
echo " If Docker fails:"
echo "  docker ps          # Check Docker daemon"
echo "  docker pull python:3.11-slim # Pull base image"
echo ""
echo " If database fails:"
echo "  docker-compose down -v    # Remove volumes"
echo "  docker-compose up -d postgres # Restart"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo " Phoenix is ready! All systems operational."
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Need help? Check the documentation:"
echo " cat QUICKSTART.md"
echo ""
